/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#2a1700',
        'tertiary-fixed': '#ffddb8',
        'surface': '#f7f9fb',
        'inverse-surface': '#2d3133',
        'tertiary-fixed-dim': '#ffb95f',
        'secondary-fixed-dim': '#a2c9ff',
        'outline': '#737781',
        'surface-container-high': '#e6e8ea',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001b3e',
        'background': '#f7f9fb',
        'on-surface': '#191c1e',
        'surface-bright': '#f7f9fb',
        'primary': '#002653',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#573500',
        'surface-dim': '#d8dadc',
        'primary-container': '#123c73',
        'tertiary': '#3a2100',
        'secondary-fixed': '#d3e4ff',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        'primary-fixed': '#d6e3ff',
        'surface-tint': '#3b5e97',
        'surface-container': '#eceef0',
        'primary-fixed-dim': '#aac7ff',
        'on-primary-fixed-variant': '#20467e',
        'inverse-primary': '#aac7ff',
        'on-secondary': '#ffffff',
        'outline-variant': '#c3c6d1',
        'on-tertiary-container': '#e89500',
        'on-primary-container': '#86a8e6',
        'error': '#ba1a1a',
        'surface-container-low': '#f2f4f6',
        'secondary': '#0060a8',
        'on-primary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'on-surface-variant': '#434750',
        'on-secondary-fixed': '#001c38',
        'secondary-container': '#47a1ff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-secondary-container': '#003663',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#004881',
        'inverse-on-surface': '#eff1f3'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px'
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans'],
        'body': ['Manrope'],
        'label': ['Manrope']
      }
    },
  },
  plugins: [],
};